### ISSUE TITLE
Error: failed to get token largest accounts

### ISSUE THREAD

**Issue by jtb0** [theskeletoncrew/air-support#4]
At first: Thank you very much for the great Tool! 

I am quite new in this topic and try to understand how this works.
I minted two NFTs at solsea. Both are stored at a Phantom wallet (diffrent wallets).
To fill the token-mint-addresses.json I used the https://tools.abstratica.art/ tool and so I get the addresses of the mints.

by running `make record DROP=1` I get the following error:
`mining HNFxv3E99iBTK6fLugPY8zMLAGDaVNxH8T3... failed. Error: failed to get token largest accounts: Invalid param: could not find mint
    at Connection.getTokenLargestAccounts (/home/marcel/Projekte/ten01/nft/air-support/1_record_holders/node_modules/@solana/web3.js/lib/index.cjs.js:3780:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async mineCurrentHolder (/home/marcel/Projekte/ten01/nft/air-support/1_record_holders/build/main.js:22:29)
    at async /home/marcel/Projekte/ten01/nft/air-support/1_record_holders/build/main.js:32:72
    at async RetryOperation._fn (/home/marcel/Projekte/ten01/nft/air-support/1_record_holders/node_modules/p-retry/index.js:50:12) {
  attemptNumber: 5,
  retriesLeft: 0
}
`
If I look at https://solscan.io/token/HNFxv3E99iBTK6fLugPY8zMLAGDaVNxH8T3... I can find the mint.

I have no idea, why the mint is not found.

Any suggestions?

**Comment by jtb0** [comment]
Ok, I got the problem. 
Makefile used the testnet and the NFTs are at the mainnet.
Changed `RPC_HOST ?= "https://api.mainnet-beta.solana.com/"` solved the Problem.
